/* Generated by Cython 0.29.30 */

#ifndef __PYX_HAVE__cython_example__cython_testing
#define __PYX_HAVE__cython_example__cython_testing

#include "Python.h"

#ifndef __PYX_HAVE_API__cython_example__cython_testing

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C int AddVals(int, int);

#endif /* !__PYX_HAVE_API__cython_example__cython_testing */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initcython_testing(void);
#else
PyMODINIT_FUNC PyInit_cython_testing(void);
#endif

#endif /* !__PYX_HAVE__cython_example__cython_testing */
